class PaginaLead < SitePrism::Page

  element :nome_evento, "#source"
  element :lead_name, "#lead_name"
  element :lead_email, "#lead_email"
  element :lead_cargo, "#lead_job_title"
  element :lead_telefone, "#lead_lead_info_attributes_personal_phone"
  element :lead_celular, "#lead_lead_info_attributes_mobile_phone"
  element :lead_twitter, "#lead_lead_info_attributes_twitter"
  element :lead_facebook, "#lead_lead_info_attributes_facebook"
  element :lead_linkedin, "#lead_lead_info_attributes_linkedin"
  element :lead_site, "#lead_lead_info_attributes_website"
  element :lead_estado, "select[id='inputUfTitle']"
  element :lead_cidade, "select[id='select2-chosen-1']"
  element :lead_empresa, "#lead_company_attributes_name"
  element :lead_setor, "#lead_company_attributes_company_sector_id"
  element :lead_tamanho, "#lead_company_attributes_size"
  element :lead_empresa_email, "#lead_company_attributes_email"
  element :lead_empresa_site, "#lead_company_attributes_site"
  element :lead_empresa_twitter, "#lead_company_attributes_twitter"
  element :lead_empresa_facebook, "#lead_company_attributes_facebook"
  element :lead_empresa_telefone, "#lead_company_attributes_phone"
  element :lead_empresa_endereco, "#lead_company_attributes_address"
  element :lead_dono_lead, "#lead_user_id"
  element :lead_anotacao, "#lead_bio"
end
